//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BibliotecaModel", "fk_area", "catalogos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BiblioTech.Entity.catalogos), "libros", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BiblioTech.Entity.libros), true)]
[assembly: EdmRelationshipAttribute("BibliotecaModel", "fk_autor", "catalogos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BiblioTech.Entity.catalogos), "libros", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BiblioTech.Entity.libros), true)]
[assembly: EdmRelationshipAttribute("BibliotecaModel", "fk_editorial", "catalogos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BiblioTech.Entity.catalogos), "libros", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BiblioTech.Entity.libros), true)]
[assembly: EdmRelationshipAttribute("BibliotecaModel", "fk_libro", "libros", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BiblioTech.Entity.libros), "perdidos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BiblioTech.Entity.perdidos), true)]
[assembly: EdmRelationshipAttribute("BibliotecaModel", "fk_libro_prestado", "libros", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BiblioTech.Entity.libros), "prestamos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BiblioTech.Entity.prestamos), true)]
[assembly: EdmRelationshipAttribute("BibliotecaModel", "fk_usuario", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BiblioTech.Entity.usuarios), "perdidos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BiblioTech.Entity.perdidos), true)]
[assembly: EdmRelationshipAttribute("BibliotecaModel", "fk_usuario_app_prestamo", "usuarios_app", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BiblioTech.Entity.usuarios_app), "prestamos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BiblioTech.Entity.prestamos), true)]
[assembly: EdmRelationshipAttribute("BibliotecaModel", "fk_usuario_prestamo", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BiblioTech.Entity.usuarios), "prestamos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BiblioTech.Entity.prestamos), true)]

#endregion

namespace BiblioTech.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BibliotecaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BibliotecaEntities usando la cadena de conexión encontrada en la sección 'BibliotecaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BibliotecaEntities() : base("name=BibliotecaEntities", "BibliotecaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BibliotecaEntities.
        /// </summary>
        public BibliotecaEntities(string connectionString) : base(connectionString, "BibliotecaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BibliotecaEntities.
        /// </summary>
        public BibliotecaEntities(EntityConnection connection) : base(connection, "BibliotecaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<catalogos> catalogos
        {
            get
            {
                if ((_catalogos == null))
                {
                    _catalogos = base.CreateObjectSet<catalogos>("catalogos");
                }
                return _catalogos;
            }
        }
        private ObjectSet<catalogos> _catalogos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<libros> libros
        {
            get
            {
                if ((_libros == null))
                {
                    _libros = base.CreateObjectSet<libros>("libros");
                }
                return _libros;
            }
        }
        private ObjectSet<libros> _libros;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<perdidos> perdidos
        {
            get
            {
                if ((_perdidos == null))
                {
                    _perdidos = base.CreateObjectSet<perdidos>("perdidos");
                }
                return _perdidos;
            }
        }
        private ObjectSet<perdidos> _perdidos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<prestamos> prestamos
        {
            get
            {
                if ((_prestamos == null))
                {
                    _prestamos = base.CreateObjectSet<prestamos>("prestamos");
                }
                return _prestamos;
            }
        }
        private ObjectSet<prestamos> _prestamos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios_app> usuarios_app
        {
            get
            {
                if ((_usuarios_app == null))
                {
                    _usuarios_app = base.CreateObjectSet<usuarios_app>("usuarios_app");
                }
                return _usuarios_app;
            }
        }
        private ObjectSet<usuarios_app> _usuarios_app;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet catalogos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocatalogos(catalogos catalogos)
        {
            base.AddObject("catalogos", catalogos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet libros. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTolibros(libros libros)
        {
            base.AddObject("libros", libros);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet perdidos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToperdidos(perdidos perdidos)
        {
            base.AddObject("perdidos", perdidos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet prestamos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToprestamos(prestamos prestamos)
        {
            base.AddObject("prestamos", prestamos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios_app. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios_app(usuarios_app usuarios_app)
        {
            base.AddObject("usuarios_app", usuarios_app);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BibliotecaModel", Name="catalogos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class catalogos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto catalogos.
        /// </summary>
        /// <param name="id_catalogo">Valor inicial de la propiedad id_catalogo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="tipo">Valor inicial de la propiedad tipo.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static catalogos Createcatalogos(global::System.Int64 id_catalogo, global::System.String descripcion, global::System.String tipo, global::System.Boolean estado)
        {
            catalogos catalogos = new catalogos();
            catalogos.id_catalogo = id_catalogo;
            catalogos.descripcion = descripcion;
            catalogos.tipo = tipo;
            catalogos.estado = estado;
            return catalogos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_catalogo
        {
            get
            {
                return _id_catalogo;
            }
            set
            {
                if (_id_catalogo != value)
                {
                    Onid_catalogoChanging(value);
                    ReportPropertyChanging("id_catalogo");
                    _id_catalogo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_catalogo");
                    Onid_catalogoChanged();
                }
            }
        }
        private global::System.Int64 _id_catalogo;
        partial void Onid_catalogoChanging(global::System.Int64 value);
        partial void Onid_catalogoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_area", "libros")]
        public EntityCollection<libros> area
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<libros>("BibliotecaModel.fk_area", "libros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<libros>("BibliotecaModel.fk_area", "libros", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_autor", "libros")]
        public EntityCollection<libros> autor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<libros>("BibliotecaModel.fk_autor", "libros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<libros>("BibliotecaModel.fk_autor", "libros", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_editorial", "libros")]
        public EntityCollection<libros> editorial
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<libros>("BibliotecaModel.fk_editorial", "libros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<libros>("BibliotecaModel.fk_editorial", "libros", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BibliotecaModel", Name="libros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class libros : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto libros.
        /// </summary>
        /// <param name="id_libro">Valor inicial de la propiedad id_libro.</param>
        /// <param name="id_area">Valor inicial de la propiedad id_area.</param>
        /// <param name="titulo">Valor inicial de la propiedad titulo.</param>
        /// <param name="no_ejemplares">Valor inicial de la propiedad no_ejemplares.</param>
        public static libros Createlibros(global::System.Int64 id_libro, global::System.Int64 id_area, global::System.String titulo, global::System.Int64 no_ejemplares)
        {
            libros libros = new libros();
            libros.id_libro = id_libro;
            libros.id_area = id_area;
            libros.titulo = titulo;
            libros.no_ejemplares = no_ejemplares;
            return libros;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_libro
        {
            get
            {
                return _id_libro;
            }
            set
            {
                if (_id_libro != value)
                {
                    Onid_libroChanging(value);
                    ReportPropertyChanging("id_libro");
                    _id_libro = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_libro");
                    Onid_libroChanged();
                }
            }
        }
        private global::System.Int64 _id_libro;
        partial void Onid_libroChanging(global::System.Int64 value);
        partial void Onid_libroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_area
        {
            get
            {
                return _id_area;
            }
            set
            {
                Onid_areaChanging(value);
                ReportPropertyChanging("id_area");
                _id_area = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_area");
                Onid_areaChanged();
            }
        }
        private global::System.Int64 _id_area;
        partial void Onid_areaChanging(global::System.Int64 value);
        partial void Onid_areaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_autor
        {
            get
            {
                return _id_autor;
            }
            set
            {
                Onid_autorChanging(value);
                ReportPropertyChanging("id_autor");
                _id_autor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_autor");
                Onid_autorChanged();
            }
        }
        private Nullable<global::System.Int64> _id_autor;
        partial void Onid_autorChanging(Nullable<global::System.Int64> value);
        partial void Onid_autorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_editorial
        {
            get
            {
                return _id_editorial;
            }
            set
            {
                Onid_editorialChanging(value);
                ReportPropertyChanging("id_editorial");
                _id_editorial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_editorial");
                Onid_editorialChanged();
            }
        }
        private Nullable<global::System.Int64> _id_editorial;
        partial void Onid_editorialChanging(Nullable<global::System.Int64> value);
        partial void Onid_editorialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String edicion
        {
            get
            {
                return _edicion;
            }
            set
            {
                OnedicionChanging(value);
                ReportPropertyChanging("edicion");
                _edicion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("edicion");
                OnedicionChanged();
            }
        }
        private global::System.String _edicion;
        partial void OnedicionChanging(global::System.String value);
        partial void OnedicionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String anio
        {
            get
            {
                return _anio;
            }
            set
            {
                OnanioChanging(value);
                ReportPropertyChanging("anio");
                _anio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("anio");
                OnanioChanged();
            }
        }
        private global::System.String _anio;
        partial void OnanioChanging(global::System.String value);
        partial void OnanioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 no_ejemplares
        {
            get
            {
                return _no_ejemplares;
            }
            set
            {
                Onno_ejemplaresChanging(value);
                ReportPropertyChanging("no_ejemplares");
                _no_ejemplares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("no_ejemplares");
                Onno_ejemplaresChanged();
            }
        }
        private global::System.Int64 _no_ejemplares;
        partial void Onno_ejemplaresChanging(global::System.Int64 value);
        partial void Onno_ejemplaresChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_area", "catalogos")]
        public catalogos area
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_area", "catalogos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_area", "catalogos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<catalogos> areaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_area", "catalogos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<catalogos>("BibliotecaModel.fk_area", "catalogos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_autor", "catalogos")]
        public catalogos autor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_autor", "catalogos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_autor", "catalogos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<catalogos> autorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_autor", "catalogos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<catalogos>("BibliotecaModel.fk_autor", "catalogos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_editorial", "catalogos")]
        public catalogos editorial
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_editorial", "catalogos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_editorial", "catalogos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<catalogos> editorialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<catalogos>("BibliotecaModel.fk_editorial", "catalogos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<catalogos>("BibliotecaModel.fk_editorial", "catalogos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_libro", "perdidos")]
        public EntityCollection<perdidos> perdidos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<perdidos>("BibliotecaModel.fk_libro", "perdidos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<perdidos>("BibliotecaModel.fk_libro", "perdidos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_libro_prestado", "prestamos")]
        public EntityCollection<prestamos> prestamos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<prestamos>("BibliotecaModel.fk_libro_prestado", "prestamos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<prestamos>("BibliotecaModel.fk_libro_prestado", "prestamos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BibliotecaModel", Name="perdidos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class perdidos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto perdidos.
        /// </summary>
        /// <param name="id_registro">Valor inicial de la propiedad id_registro.</param>
        /// <param name="id_libro">Valor inicial de la propiedad id_libro.</param>
        /// <param name="fecha_perdida">Valor inicial de la propiedad fecha_perdida.</param>
        /// <param name="matricula">Valor inicial de la propiedad matricula.</param>
        public static perdidos Createperdidos(global::System.Int64 id_registro, global::System.Int64 id_libro, global::System.DateTime fecha_perdida, global::System.String matricula)
        {
            perdidos perdidos = new perdidos();
            perdidos.id_registro = id_registro;
            perdidos.id_libro = id_libro;
            perdidos.fecha_perdida = fecha_perdida;
            perdidos.matricula = matricula;
            return perdidos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_registro
        {
            get
            {
                return _id_registro;
            }
            set
            {
                if (_id_registro != value)
                {
                    Onid_registroChanging(value);
                    ReportPropertyChanging("id_registro");
                    _id_registro = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_registro");
                    Onid_registroChanged();
                }
            }
        }
        private global::System.Int64 _id_registro;
        partial void Onid_registroChanging(global::System.Int64 value);
        partial void Onid_registroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_libro
        {
            get
            {
                return _id_libro;
            }
            set
            {
                Onid_libroChanging(value);
                ReportPropertyChanging("id_libro");
                _id_libro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_libro");
                Onid_libroChanged();
            }
        }
        private global::System.Int64 _id_libro;
        partial void Onid_libroChanging(global::System.Int64 value);
        partial void Onid_libroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_perdida
        {
            get
            {
                return _fecha_perdida;
            }
            set
            {
                Onfecha_perdidaChanging(value);
                ReportPropertyChanging("fecha_perdida");
                _fecha_perdida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_perdida");
                Onfecha_perdidaChanged();
            }
        }
        private global::System.DateTime _fecha_perdida;
        partial void Onfecha_perdidaChanging(global::System.DateTime value);
        partial void Onfecha_perdidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String matricula
        {
            get
            {
                return _matricula;
            }
            set
            {
                OnmatriculaChanging(value);
                ReportPropertyChanging("matricula");
                _matricula = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("matricula");
                OnmatriculaChanged();
            }
        }
        private global::System.String _matricula;
        partial void OnmatriculaChanging(global::System.String value);
        partial void OnmatriculaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_libro", "libros")]
        public libros libros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("BibliotecaModel.fk_libro", "libros").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("BibliotecaModel.fk_libro", "libros").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<libros> librosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("BibliotecaModel.fk_libro", "libros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<libros>("BibliotecaModel.fk_libro", "libros", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_usuario", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("BibliotecaModel.fk_usuario", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("BibliotecaModel.fk_usuario", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("BibliotecaModel.fk_usuario", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("BibliotecaModel.fk_usuario", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BibliotecaModel", Name="prestamos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class prestamos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto prestamos.
        /// </summary>
        /// <param name="id_prestamo">Valor inicial de la propiedad id_prestamo.</param>
        /// <param name="matricula">Valor inicial de la propiedad matricula.</param>
        /// <param name="fecha_prestamo">Valor inicial de la propiedad fecha_prestamo.</param>
        /// <param name="fecha_entrega_sugerida">Valor inicial de la propiedad fecha_entrega_sugerida.</param>
        /// <param name="id_usuario_app">Valor inicial de la propiedad id_usuario_app.</param>
        /// <param name="id_libro">Valor inicial de la propiedad id_libro.</param>
        public static prestamos Createprestamos(global::System.Int64 id_prestamo, global::System.String matricula, global::System.DateTime fecha_prestamo, global::System.DateTime fecha_entrega_sugerida, global::System.Int64 id_usuario_app, global::System.Int64 id_libro)
        {
            prestamos prestamos = new prestamos();
            prestamos.id_prestamo = id_prestamo;
            prestamos.matricula = matricula;
            prestamos.fecha_prestamo = fecha_prestamo;
            prestamos.fecha_entrega_sugerida = fecha_entrega_sugerida;
            prestamos.id_usuario_app = id_usuario_app;
            prestamos.id_libro = id_libro;
            return prestamos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_prestamo
        {
            get
            {
                return _id_prestamo;
            }
            set
            {
                if (_id_prestamo != value)
                {
                    Onid_prestamoChanging(value);
                    ReportPropertyChanging("id_prestamo");
                    _id_prestamo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_prestamo");
                    Onid_prestamoChanged();
                }
            }
        }
        private global::System.Int64 _id_prestamo;
        partial void Onid_prestamoChanging(global::System.Int64 value);
        partial void Onid_prestamoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String matricula
        {
            get
            {
                return _matricula;
            }
            set
            {
                OnmatriculaChanging(value);
                ReportPropertyChanging("matricula");
                _matricula = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("matricula");
                OnmatriculaChanged();
            }
        }
        private global::System.String _matricula;
        partial void OnmatriculaChanging(global::System.String value);
        partial void OnmatriculaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_prestamo
        {
            get
            {
                return _fecha_prestamo;
            }
            set
            {
                Onfecha_prestamoChanging(value);
                ReportPropertyChanging("fecha_prestamo");
                _fecha_prestamo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_prestamo");
                Onfecha_prestamoChanged();
            }
        }
        private global::System.DateTime _fecha_prestamo;
        partial void Onfecha_prestamoChanging(global::System.DateTime value);
        partial void Onfecha_prestamoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_entrega_sugerida
        {
            get
            {
                return _fecha_entrega_sugerida;
            }
            set
            {
                Onfecha_entrega_sugeridaChanging(value);
                ReportPropertyChanging("fecha_entrega_sugerida");
                _fecha_entrega_sugerida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_entrega_sugerida");
                Onfecha_entrega_sugeridaChanged();
            }
        }
        private global::System.DateTime _fecha_entrega_sugerida;
        partial void Onfecha_entrega_sugeridaChanging(global::System.DateTime value);
        partial void Onfecha_entrega_sugeridaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_entrega_real
        {
            get
            {
                return _fecha_entrega_real;
            }
            set
            {
                Onfecha_entrega_realChanging(value);
                ReportPropertyChanging("fecha_entrega_real");
                _fecha_entrega_real = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_entrega_real");
                Onfecha_entrega_realChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_entrega_real;
        partial void Onfecha_entrega_realChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_entrega_realChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario_app
        {
            get
            {
                return _id_usuario_app;
            }
            set
            {
                Onid_usuario_appChanging(value);
                ReportPropertyChanging("id_usuario_app");
                _id_usuario_app = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_app");
                Onid_usuario_appChanged();
            }
        }
        private global::System.Int64 _id_usuario_app;
        partial void Onid_usuario_appChanging(global::System.Int64 value);
        partial void Onid_usuario_appChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_libro
        {
            get
            {
                return _id_libro;
            }
            set
            {
                Onid_libroChanging(value);
                ReportPropertyChanging("id_libro");
                _id_libro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_libro");
                Onid_libroChanged();
            }
        }
        private global::System.Int64 _id_libro;
        partial void Onid_libroChanging(global::System.Int64 value);
        partial void Onid_libroChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_libro_prestado", "libros")]
        public libros libros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("BibliotecaModel.fk_libro_prestado", "libros").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("BibliotecaModel.fk_libro_prestado", "libros").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<libros> librosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("BibliotecaModel.fk_libro_prestado", "libros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<libros>("BibliotecaModel.fk_libro_prestado", "libros", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_usuario_app_prestamo", "usuarios_app")]
        public usuarios_app usuarios_app
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios_app>("BibliotecaModel.fk_usuario_app_prestamo", "usuarios_app").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios_app>("BibliotecaModel.fk_usuario_app_prestamo", "usuarios_app").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios_app> usuarios_appReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios_app>("BibliotecaModel.fk_usuario_app_prestamo", "usuarios_app");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios_app>("BibliotecaModel.fk_usuario_app_prestamo", "usuarios_app", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_usuario_prestamo", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("BibliotecaModel.fk_usuario_prestamo", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("BibliotecaModel.fk_usuario_prestamo", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("BibliotecaModel.fk_usuario_prestamo", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("BibliotecaModel.fk_usuario_prestamo", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BibliotecaModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="matricula">Valor inicial de la propiedad matricula.</param>
        /// <param name="primer_nombre">Valor inicial de la propiedad primer_nombre.</param>
        /// <param name="apellido_materno">Valor inicial de la propiedad apellido_materno.</param>
        /// <param name="tipo_usuario">Valor inicial de la propiedad tipo_usuario.</param>
        public static usuarios Createusuarios(global::System.String matricula, global::System.String primer_nombre, global::System.String apellido_materno, global::System.String tipo_usuario)
        {
            usuarios usuarios = new usuarios();
            usuarios.matricula = matricula;
            usuarios.primer_nombre = primer_nombre;
            usuarios.apellido_materno = apellido_materno;
            usuarios.tipo_usuario = tipo_usuario;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String matricula
        {
            get
            {
                return _matricula;
            }
            set
            {
                if (_matricula != value)
                {
                    OnmatriculaChanging(value);
                    ReportPropertyChanging("matricula");
                    _matricula = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("matricula");
                    OnmatriculaChanged();
                }
            }
        }
        private global::System.String _matricula;
        partial void OnmatriculaChanging(global::System.String value);
        partial void OnmatriculaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String primer_nombre
        {
            get
            {
                return _primer_nombre;
            }
            set
            {
                Onprimer_nombreChanging(value);
                ReportPropertyChanging("primer_nombre");
                _primer_nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("primer_nombre");
                Onprimer_nombreChanged();
            }
        }
        private global::System.String _primer_nombre;
        partial void Onprimer_nombreChanging(global::System.String value);
        partial void Onprimer_nombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String segundo_nombre
        {
            get
            {
                return _segundo_nombre;
            }
            set
            {
                Onsegundo_nombreChanging(value);
                ReportPropertyChanging("segundo_nombre");
                _segundo_nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("segundo_nombre");
                Onsegundo_nombreChanged();
            }
        }
        private global::System.String _segundo_nombre;
        partial void Onsegundo_nombreChanging(global::System.String value);
        partial void Onsegundo_nombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido_paterno
        {
            get
            {
                return _apellido_paterno;
            }
            set
            {
                Onapellido_paternoChanging(value);
                ReportPropertyChanging("apellido_paterno");
                _apellido_paterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellido_paterno");
                Onapellido_paternoChanged();
            }
        }
        private global::System.String _apellido_paterno;
        partial void Onapellido_paternoChanging(global::System.String value);
        partial void Onapellido_paternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido_materno
        {
            get
            {
                return _apellido_materno;
            }
            set
            {
                Onapellido_maternoChanging(value);
                ReportPropertyChanging("apellido_materno");
                _apellido_materno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido_materno");
                Onapellido_maternoChanged();
            }
        }
        private global::System.String _apellido_materno;
        partial void Onapellido_maternoChanging(global::System.String value);
        partial void Onapellido_maternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo_usuario
        {
            get
            {
                return _tipo_usuario;
            }
            set
            {
                Ontipo_usuarioChanging(value);
                ReportPropertyChanging("tipo_usuario");
                _tipo_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo_usuario");
                Ontipo_usuarioChanged();
            }
        }
        private global::System.String _tipo_usuario;
        partial void Ontipo_usuarioChanging(global::System.String value);
        partial void Ontipo_usuarioChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_usuario", "perdidos")]
        public EntityCollection<perdidos> perdidos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<perdidos>("BibliotecaModel.fk_usuario", "perdidos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<perdidos>("BibliotecaModel.fk_usuario", "perdidos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_usuario_prestamo", "prestamos")]
        public EntityCollection<prestamos> prestamos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<prestamos>("BibliotecaModel.fk_usuario_prestamo", "prestamos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<prestamos>("BibliotecaModel.fk_usuario_prestamo", "prestamos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BibliotecaModel", Name="usuarios_app")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios_app : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios_app.
        /// </summary>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="nombre_usuario">Valor inicial de la propiedad nombre_usuario.</param>
        /// <param name="contrasenia">Valor inicial de la propiedad contrasenia.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="nombre_completo">Valor inicial de la propiedad nombre_completo.</param>
        /// <param name="permisos">Valor inicial de la propiedad permisos.</param>
        public static usuarios_app Createusuarios_app(global::System.Int64 id_usuario, global::System.String nombre_usuario, global::System.String contrasenia, global::System.Boolean estado, global::System.String nombre_completo, global::System.String permisos)
        {
            usuarios_app usuarios_app = new usuarios_app();
            usuarios_app.id_usuario = id_usuario;
            usuarios_app.nombre_usuario = nombre_usuario;
            usuarios_app.contrasenia = contrasenia;
            usuarios_app.estado = estado;
            usuarios_app.nombre_completo = nombre_completo;
            usuarios_app.permisos = permisos;
            return usuarios_app;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int64 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int64 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_usuario
        {
            get
            {
                return _nombre_usuario;
            }
            set
            {
                Onnombre_usuarioChanging(value);
                ReportPropertyChanging("nombre_usuario");
                _nombre_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_usuario");
                Onnombre_usuarioChanged();
            }
        }
        private global::System.String _nombre_usuario;
        partial void Onnombre_usuarioChanging(global::System.String value);
        partial void Onnombre_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasenia
        {
            get
            {
                return _contrasenia;
            }
            set
            {
                OncontraseniaChanging(value);
                ReportPropertyChanging("contrasenia");
                _contrasenia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasenia");
                OncontraseniaChanged();
            }
        }
        private global::System.String _contrasenia;
        partial void OncontraseniaChanging(global::System.String value);
        partial void OncontraseniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_completo
        {
            get
            {
                return _nombre_completo;
            }
            set
            {
                Onnombre_completoChanging(value);
                ReportPropertyChanging("nombre_completo");
                _nombre_completo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_completo");
                Onnombre_completoChanged();
            }
        }
        private global::System.String _nombre_completo;
        partial void Onnombre_completoChanging(global::System.String value);
        partial void Onnombre_completoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String permisos
        {
            get
            {
                return _permisos;
            }
            set
            {
                OnpermisosChanging(value);
                ReportPropertyChanging("permisos");
                _permisos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("permisos");
                OnpermisosChanged();
            }
        }
        private global::System.String _permisos;
        partial void OnpermisosChanging(global::System.String value);
        partial void OnpermisosChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BibliotecaModel", "fk_usuario_app_prestamo", "prestamos")]
        public EntityCollection<prestamos> prestamos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<prestamos>("BibliotecaModel.fk_usuario_app_prestamo", "prestamos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<prestamos>("BibliotecaModel.fk_usuario_app_prestamo", "prestamos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
